### ISSUE TITLE
capturing excerpts for pages

### ISSUE THREAD

**Issue by BryanSchuetz** [algolia/jekyll-algolia#41]
## I want to report a bug:

**What is the current behavior?**
the excerpt in the algolia record does not capture excerpts for pages, it only seems to grab them for posts or documents

**What is your expected behavior?**
I would expect a record for a page to also have excerpt_text available
**Steps to reproduce the issue:**

**Comment by pixelastic** [comment]
Hello,

This seems to be a limitation of Jekyll itself. Pages don't seem to have an excerpt available, only documents do (posts are a special handling of documents).

I filed an issue on Jekyll itself about it: https://github.com/jekyll/jekyll/issues/6778

I'm going to close this issue for now as there isn't much I can do about it. 

Can I ask what your use-case was, so I can see if I can find another solution?

**Comment by BryanSchuetz** [comment]
I see. Didn't realize pages don't generate an excerpt. They should change that probably, will go comment on the issue.

I was using `excerpt_text` in my hits widget—so obviously when pages are returned as a result, the snippet is empty. I'm currently getting around it by retrieving a summary attribute that exists on pages and displaying that if there is no excerpt: `{{^excerpt_text}}{{{_snippetResult.summary.value}}}{{/excerpt_text}}`. But this is a bit hacky I think. 

I guess the alternative approach is to just snippet the `html` attribute for both posts and pages? I don't currently have that set to be retrieved or searchable so I'm not sure if Jekyll-Algolia is putting anything there?

**Comment by pixelastic** [comment]
> I guess the alternative approach is to just snippet the html attribute for both posts and pages? I don't currently have that set to be retrieved or searchable so I'm not sure if Jekyll-Algolia is putting anything there?

The default plugin configuration will return a snippet version of both `content` and `html`, so you can use that. This might actually be even better, depending on context, as this will output the actual paragraph of text that is matching your keywords.

In the meantime, there is an active PR in Jekyll itself to add `excerpt` to pages, so this might even land soon.

**Comment by BryanSchuetz** [comment]
If I'm already setting `attributesToSnippet` on my results page will I need to add it there? How would I reference it in the hits widget template, `{{_snippetResult.content.value}}`? Is there a list somewhere of all the default attributes that get added to the record when it's sent to the index?

**Comment by pixelastic** [comment]
Oh sorry, I think what I said wasn't completely right. An **highlight** version will be automatically returned for `html` and `text`. If you want snippeting as well, you have [to pass it](https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/) (either during the search call, or as a global setting on the index). It seems you're doing it on during search, which is totally fine, I just wanted to be thorough and let you know you can also define directly on the index if needed :)

So yeah, just like you defined `summary`, you can define `content` as well. I would suggest **not** to do snipeting on `html` as it might break the HTML parser because it might open (close) tags that won't be properly closed (opened).

You can find an example of a record, with all keys here: https://community.algolia.com/jekyll-algolia/how-it-works.html but the best way would be to check directly from your [Algolia dashboard](https://www.algolia.com/) where you'll actually be able to search into all your records.
