### ISSUE TITLE
bug report, jekyll-algolia on safari of iOS 9.0 couldn't disappear normally.

### ISSUE THREAD

**Issue by yefeiyu** [algolia/jekyll-algolia#57]
## I want to report a bug:
When I put the jekyll-algolia on my blog, I found it didn't appear normal on the Safari or Chrome of iOS 9.0 of the iphone 6s plus.
Other explore's appear is good.

The example web is : http://gaeblogx.com/search/, which github project is 
SeraphRoy/SeraphRoy.github.io
or my site: http://yefeiyu.github.io/search/
(github site is yefeiyu/yefeiyu.github.io)
Now, I put the pictures on here, the same site on different mobile, one is 5s, the other is 6s plus.
![5s1](https://user-images.githubusercontent.com/4845104/37902570-629da1da-3127-11e8-97cc-984272636c75.jpg)
picture 1 : on 5s 
![811357562](https://user-images.githubusercontent.com/4845104/37902575-67fd3582-3127-11e8-8935-3b7046c08dab.jpg) 
picture 2 : on 6s plus
![5s2](https://user-images.githubusercontent.com/4845104/37902578-6c3089f6-3127-11e8-852b-e6057b5669fa.jpg) 
picture 3: on 5s
![1992292266](https://user-images.githubusercontent.com/4845104/37902584-6fbd6ab2-3127-11e8-9717-0ec1e984ef5b.jpg) 
picture 4: on 6s plus

**Comment by pixelastic** [comment]
Hello,

Sorry you're having display issues. The jekyll-algolia plugin only take care of the indexing of the posts; I'll do my best to help you with the display issues but you might have a better chance by asking in the [instantsearch.js issues](https://github.com/algolia/instantsearch.js/issues).


Still, I see that you are using instantsearch.js v2.3.0. Could you try with the latest (v2.6.0) and see if the issue is still present?

**Comment by yefeiyu** [comment]
Thank you, I'll report to instantsearch.js

**Comment by pixelastic** [comment]
I'm reopening the issue as it seems it might be coming from the plugin. It seems that some of your records don't have an `html` attribute, which should not happen.

**Comment by yefeiyu** [comment]
When I use `conkeror` or iphone which system is iOS 9.0 open the [https://algolia.github.io](https://algolia.github.io) ,I got the same error, there is none search box.
And, further, the `conkeror` browser crashed.
The screenshots below:
![2018-03-30](https://user-images.githubusercontent.com/4845104/38122148-e6e1fc14-33c2-11e8-9284-488f792ac344.png)

![2092611494](https://user-images.githubusercontent.com/4845104/38122138-db634122-33c2-11e8-876b-a1451b57a42a.jpg)
![1946497446](https://user-images.githubusercontent.com/4845104/38122143-df2e8438-33c2-11e8-814c-c0bd6a7860d6.jpg)

**Comment by pixelastic** [comment]
Oh I see. The code examples used on the documentation website are using some JavaScript features that are not available in all browsers, that's why it's failing on some of the old browsers you'rs testing on. 

I'll add a note to the documentation about that, but in your case it will mean slightly rewriting the code (or using [babel](https://babeljs.io/) to do it automatically)

- String templates should be replaced with string concatenation (`'<span class="post-meta">' + date + '</span>'`)
- `const` / `let` should be replaced with `var`
- Arrow functions should be replaced with `function() {}`

I am going to file an issue on our side about the https://community.algolia.com/ website not working on old browsers as well.

Thanks for the report!
