### ISSUE TITLE
<pre> indexing issue

### ISSUE THREAD

**Issue by jonaprieto** [algolia/jekyll-algolia#63]
This issue was mention in #45.
In my repository (https://github.com/jonaprieto/jonaprieto.github.io/)
I'm having this problem trying to index pre blocks.

I got this:

```
$ jekyll algolia
...
jekyll 3.7.2 | Error:  undefined method `[]' for nil:NilClass
```

**Comment by jonaprieto** [comment]
I removed the `Gemfile.lock` file before running `bundle install`. It solved the problem. ;)

On the other hand, a new warning arose about a record rejected (it wasn't rejected before).

```
The plugin will create one record for each element matching your
`nodes_to_index` value (currently set to "p,blockquote,pre").
Each record should not weight more than 10 Kb.
One of your records weights 36.53 Kb and has been rejected.

objectID: 70ab979b94368fbdd51f944ee98b6eba
title:    Univalence From Scratch
url:      /type-theory/2018/03/17/univalence-from-scratch/
```

It seems, I'm possibly wrong, but algolia should ignore the meta information in the `a` tags? because that post in particular, is too short. There are other much bigger and no rejected.

**Comment by pixelastic** [comment]
Because you defined `pre` as one of the `nodes_to_index`, the plugin will now create one record for each `pre` of your content. It will set the `html` key of this record to the HTML content of the `pre`, and the `content` key to its textual version (removing the HTML markup).

We store both keys because depending on your UI you might want to display the results with full HTML (links, images, etc) or just a short snippet.

Turns out that the `html` version of your `pre` tags are pretty verbose, as it adds an `href` to the current page to almost every symbol. The resulting output is too big to fit in a record.

I'm reluctant to fix this from the jekyll-algolia plugin itself as it seems overly specific to your use-case and plugin combination. What I would suggest instead is to write a custom hook that would remove all the unneeded markup from your records before pushing them. 

The [before_indexing_each](https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-each) is made for that. It takes a record and the HTML representation of the node as input, allows you to manipulate it, and return the new version of the record.

_⚠ Unfortunately, I just realize that it is not possible to define custom hooks when using the `github-pages` (that you are also using) gem as this gem disable the use of any custom plugin. I'm going to check if there is another way to define hooks._

- Index the .ladga

**Comment by pixelastic** [comment]
I found a way to bypass the issue with the `github-pages` gem. I'll add more tests to it and release a new version. I'll also post a hook to fix your specific issue. Should take a few days, though as I'll be on a plane in the coming days :)

**Comment by jonaprieto** [comment]
It works perfectly. Thank you very much for your dedication. 👍
