### ISSUE TITLE
jekyll algolia push broken with jekyll-redirect-from

### ISSUE THREAD

**Issue by rickychilcott** [algolia/jekyll-algolia#80]
Thank you for building and maintaining this jekyll plugin. It has made integrating algolia into my project pretty easy.

## I want to report a bug: 

Adding `jekyll-redirect-from` plugin causes `jekyll algolia push` to error on index building.

### What is the current behavior?

I added the jekyll-redirect-from plugin, and then the following to the top of a markdown file

```
---
layout: default
redirect_to: https://www.google.com
---
```

`jekyll agolia push`

Now errors with:

`jekyll 3.8.3 | Error:  No such file or directory - /home/circleci/project/src/redirect.html does not exist!`

NOTE: I'm using Circle CI to build my algolia index.

I can fix this by creating a (blank) file `touch src/redirect.html`, but it's confusing because https://github.com/jekyll/jekyll-redirect-from#customizing-the-redirect-template suggests I should be building a custom layout that looks like https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect.html and that doesn't fix it. Only touching that redirect.html file fixes the problem.

https://github.com/algolia/jekyll-algolia/blob/e7a0dc32c530dc680a13aefe552afa2787034d5d/lib/jekyll/algolia/file_browser.rb#L85 suggests that this has already been dealt with before, but I'm not sure exactly what's causing it.

### What is your expected behavior?

Ability to use jekyll-redirect-from without creating the dummy file.

### Git repository to reproduce the issue:
I could create one if it would be really helpful, but this project isn't open source unfortunately

### Ruby version used:
ruby 2.5.1p57

### Jekyll version used:
jekyll 3.8.3

**Comment by pixelastic** [comment]
Thanks for the report,

As you found in the code, I thought I already fixed a similar issue in the past but there might be something missing here.

If you could create a test repo for me to reproduce the issue, that would greatly help my investigation :)

**Comment by rickychilcott** [comment]
Repo is at https://github.com/Rakefire/algolia-and-jekyll-redirect-fail

Some tips that might be useful to get it building:

- edit `_config.yml` to add the relevant `algolia` config settings for a project
- add a `.env` file to the project root with something like `ALGOLIA_API_KEY='api-key'`.
- This one is a little special since it uses webpack to build some assets. You'll need to run `bin/install` to get all of the npm modules installed. And then `bin/start` to start webpack and jekyll serving.
- Lastly, `bin/update-algolia` to test.

It may be that the source (no pun intended) of the problem is that `source: src` is configured in the `_config.yml`, but that might not be it at all.

Thanks for your help!

**Comment by pixelastic** [comment]
Thanks for the repo link. I'll try to have a look shortly!

**Comment by pixelastic** [comment]
Hey, just a heads up that I managed to reproduce the issue on my side. I'm investigating.

**Comment by rickychilcott** [comment]
Thanks!

**Comment by pixelastic** [comment]
The issue was that I wasn't handling the `redirect_to` option of `jekyll-redirect-from` plugin, but only the `redirect_from` one. I now exclude from indexing any file that has its layout set to `redirect` (this is what the plugin does internally, and I assumed any file using a layout named that way can be safely excluded from search results)

I just release v1.4.8 that should have your issue fixed. Could you check on your side and confirm?

**Comment by rickychilcott** [comment]
Fantastic. That works. Thank you @pixelastic!

**Comment by pixelastic** [comment]
Perfect, thanks for checking :)

**Comment by jeff-matthews** [comment]
@pixelastic, if I'm understanding this correctly, the expected behavior is to ignore files that contain "redirect" metadata.

However, it could still be useful to index content in a redirected file. For example, migrating content to a new site. Continuing to provide search results for content, even if they redirect to another site, could help preserve the discoverability of content. Ignoring the files creates a sort of gap in discoverability while the migration takes place.

What recommendations do you have for indexing files with redirect metadata?
