### ISSUE TITLE
Record too large due to frontmatter

### ISSUE THREAD

**Issue by cameronmcefee** [algolia/jekyll-algolia#98]
## I want to report a bug:

I'm not sure this qualifies as an error, I probably just don't understand what Algolia is trying to do.

### What is the current behavior?

I receive "record is too big" errors attributed to frontmatter keys. Nothing in the docs that I've seen indicates that frontmatter is indexed as well. The frontmatter in question gets rendered in the page, but isn't rendered in a `p` so I assume it would be skipped.

Source of the page in question: https://github.com/getsentry/sentry-docs/blob/algolia/src/collections/_documentation/api/events/get-group-events-oldest.md

```
title:    Retrieve Oldest Event
url:      /api/events/get-group-events-oldest/
size:     48.74 Kb

Most probable keys causing the issue:
   example_response (44.24 Kb), example_request (0.11 Kb), path_parameters (0.08
Kb)

Complete log of the record has been extracted to:
   src/jekyll-algolia-record-too-big.log
```

### What is your expected behavior?

The frontmatter should be ignored (or I'd like an option to exclude keys if it *does* get indexed) and the page should be processed correctly.

### Git repository to reproduce the issue:

See this branch: https://github.com/getsentry/sentry-docs/tree/algolia

Run `bin/algolia` to reproduce

### Ruby version used:

ruby 2.4.2p198

### Jekyll version used:

jekyll 3.8.3

**Comment by pixelastic** [comment]
Hello and thanks for the report,

All front-matter fields are indexed by default and added to each record extracted from a page. I did that in order to allow people to filter results or tweak the ranking based on custom values of the front-end (like setting a `language: en` or `is_awesome: true`).

In your case, that is not a desirable behavior as your front-matter is pretty large. I would recommend setting a custom `before_indexing_each` hook to cleanup fields from the front-matter you don't want to index. [before_indexing_each](https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-each) is called on every record right before they are pushed and gives you an opportunity to modify them (adding/deleting/editing keys). If you delete the key(s) you don't want in that method and return the modified record, you should be able to workaround the "record is too big" issue.

Hope that helps,

**Comment by cameronmcefee** [comment]
Awesome, thanks @pixelastic, that seems sensible.
