### ISSUE TITLE
Only indexes first paragraph of markdown file

### ISSUE THREAD

**Issue by damcclean** [algolia/jekyll-algolia#99]
### What is the current behavior?
Only the first paragraph of my markdown files are being uploaded to the 'content' section of each indexed item.

### What is your expected behavior?
For all of my markdown content to be uploaded to the 'content' section of each indexed item.

### Screenshots
![My indexed items](https://cdn-std.dprcdn.net/files/acc_635918/KZfnyd)
![My content of the pages](https://cdn-std.dprcdn.net/files/acc_635918/Yn5LrU)

### Ruby version used:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

### Jekyll version used:
jekyll 3.8.4

**Comment by pixelastic** [comment]
Hello and thanks for the report,

This is not a bug, this is a feature ;)

I know it can sound strange, but all the paragraphs of your records are **actually** indexed. What is happening is that you only **see** the first one in your Algolia dashboard.

This is because each paragraph is indexed as a separate record, but all paragraphs of the same page share the same `url` key, and this key is used for the `distinct` feature of Algolia. What it does is that if several records are matching your request, only one for each `url` will be displayed. And the one displayed is always the "most relevant one" (as configured in the ranking formula). In your case, with an empty search query, the most relevant is considered to be the first one.

You can try searching for text that is present in the 2nd or 3rd paragraph and you'll see them displayed in the results. If you want to see absolutely all the indexed records, you should click on "Add query parameter" in your dashboard and set distinct to false:
![image](https://user-images.githubusercontent.com/283419/47714360-ef8ddb80-dc3c-11e8-88eb-d07b1a8c9967.png)

Hope that helps clarify the issue; all your content should still be searchable

**Comment by damcclean** [comment]
Oh, sorry. Thanks for the explanation 👍

**Comment by pixelastic** [comment]
No worries :)
